### ISSUE TITLE
[QUESTION] Why is auto-session incompatible with Firenvim?

### ISSUE THREAD

**Issue by glacambre** [rmagatti/auto-session#114]
Hi, Firenvim's maintainer here :). Somebody recently opened [an issue](https://github.com/glacambre/firenvim/issues/1306) in Firenvim's repo and figured out that their problem came from combining Firenvim and auto-session.

When the user opens their browser, the firenvim browser add-on spawns neovim, without any file arguments (but with multiple `--headless`, `-c` and `--cmd` arguments). Then, later on, when the user clicks on a textarea, the firenvim browser add-on connects to neovim through a websocket and uses neovim's `writefile()` function to create a file with the textarea's content on the user's disk (note that the file's name contains a timestamp and thus should be unique). Once the file is created, firenvim runs an `:edit` command to open this file in neovim.

I don't know what auto-session does and how it works, so I have hard time imagining how what firenvim does could result in the `auto-session/lua/auto-session-library.lua:189:         Error restoring session! The session might be corrupted.` error. Do you have an idea of what might be happening?

**Comment by rmagatti** [comment]
Hi @glacambre thanks for reaching out! auto-session throws that message when the loading of a session (source session_file.vim) results in an error. You mentioned Firenvim opens neovim without file arguments, that is actually a trigger for auto-session to try and load up a session for the `cwd` dir if it finds one.

What I recommend is disabling auto-session when Neovim is started by Firenvim. In fact that's exactly what I do in my config, as I didn't think having persistent sessions across firenvim starts would be of any use.

This is the snippet I have in my lua config currently.
```lua
if vim.g.started_by_firenvim == 1 then
  vim.g.auto_session_enabled = false
end
```

PS: big fan of Firenvim here, I use it every day! :)

**Comment by glacambre** [comment]
>when the loading of a session (source session_file.vim) results in an error.

Do you know what is causing an error to be thrown while loading this session file? My understanding of session files is that they're just a dump of settings/variables, I'm not sure why loading one would cause an error.

>PS: big fan of Firenvim here, I use it every day! :)

Thanks, auto-session seems pretty cool too! :)

**Comment by rmagatti** [comment]
It's kind of hard to tell without looking at the specific config and session file (and even then it's a bit hard to tell). It's not necessarily the loading of the settings that is erroring, but say after the settings are loaded something in the user's config immediately throws an error, that would also do it. I've had this happen when say some fold isn't found and Neovim throws that No fold found error while loading a session. The idea with this is to avoid potentially saving something in a session that is actually in a corrupted state.

Just to be clear, auto-session is actually compatible with Firenvim, one can actually have successful sessions saved and restored when using Firenvim, I mostly recommend disabling it because I don't really see why someone would want persistent Firenvim sessions.

If a session is corrupted i.e throwing that error, they can run `:DeleteSession` from an instance that has tried to load the "corrupted" session and start over again.

**Comment by glacambre** [comment]
I see, thanks for your insights. In any case, I made Firenvim much more robust with https://github.com/neovim/neovim/pull/15910 , https://github.com/neovim/neovim/pull/17199 and https://github.com/glacambre/firenvim/pull/1294 , so when Neovim 0.7.0 is releaseed session-loading issues should not break Firenvim anymore.

Thanks a lot for answering my questions! :)
