### ISSUE TITLE
[BUG] Lsp clients are not attached on all open windows

### ISSUE THREAD

**Issue by vycoder** [rmagatti/auto-session#165]
**Describe the bug**
Whenever I reopen a session, I noticed that it only attaches the LSP clients of the currently active window. I had to go over the other windows run `:LspStart` before everything to work as expected.

I'm just using the default config from the README, not sure if I need to do something else.

Here's my setup config.
```lua
.setup({
   log_level ="error",
   auto_session_suppress_dirs = { "/", "~/", "~/Downloads" },
   cwd_change_handling = {
      post_cwd_changed_hook = function()
         require("lualine").refresh()
      end
   }
})
```

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal
 - OS. e.g `uname -a`: Pop!_OS 22.04 LTS
 - Neovim version `nvim --version`: v0.7.2

**Additional context**
I'm using NVChad as a base, I'm really just a newbie in this whole neovim thing.

**Comment by rmagatti** [comment]
Hey @vycoder. Thanks for the issue submission!

This isn't really something this plugin has control over at all. Sessions are a native Vim/Neovim feature, all auto-session does is wrap its functionality to make it automatic and seamless. What I can tell you is that my config doesn't seem to have the issue you're mentioning, lsp servers usually use a project root dir (your cwd) if I'm not mistaken, so if you've got things configured correctly for your lsp client you when a session loads so should the lsp client since client load is usually attatched to some sort of buffer load autocmds.

**Comment by vycoder** [comment]
Okay, I see. I figured it's probably because my config lazy-loads lspconfig, that must've been the one causing this issue. Or probably something related to it.

Closing this issue, I'm apparently submitting an issue to the wrong place. Thanks for responding anyway! Thanks again!

**Comment by tan-wei** [comment]
@vycoder I just met the same issue. I wonder if you have solve this? Thanks!
