### ISSUE TITLE
Prevent opening a session if one or more of the file

### ISSUE THREAD

**Issue by urandom** [rmagatti/auto-session#3]
Currently, if someone already has an open session (or is editing a file that's also part of an existing session), when starting a new nvim instance, it will complain that the file is already opened and ask for deletion/restoration/etc. If this can somehow be detected, perhaps it's better if loading the session be aborted with a message saying that one or more of the files are already opened somewhere.

**Comment by rmagatti** [comment]
Hey @urandom are you talking about vim's default behaviour when opening the same file on different vim instances? The plugin doesn't touch anything regarding that behaviour currently.

I'm assuming you don't have `set noswapfile` in your config?

**Comment by urandom** [comment]
@rmagatti 
Yes, this is specific with the interaction of vim's default behavior (the dialog for recovering/deleting/opening a file as read-only). Also, no, my swap files are enabled.

**Comment by rmagatti** [comment]
@urandom okay so thought a bit about this. I don't think aborting session loading in that case is ideal. But before I go any further, what happens if more than one file is already opened on some other vim instance? Does it "queue" up those messages about deletion/restoration/etc or does it basically only show the last one? (or something else?) Admittedly I haven't tested this specific scenario yet but figured I'd ask first anyway.

**Comment by urandom** [comment]
@rmagatti it shows as many messages as there are already open files.

**Comment by rmagatti** [comment]
Hey @urandom coming back to this after a while.

So I don't think a change in behaviour here is desired since this is just Vim's default behaviour with swap files, regardless of session loading.

There's also the fact that I'm not sure how I'd be able to "abort" the session loading since this it's also just Vim's default session management happening; the plugin just automates some of it through a few sensible defaults.

**Comment by urandom** [comment]
@rmagatti 
Makes sense. Then I'll close this issue. Thanks

**Comment by ErikEkstedt** [comment]
Hello, first of very nice plugin!

I use the following settings (from [greg hurrell's video](https://youtu.be/fm33-Pas7vI?t=193) ) that handles open files and swaps etc.

```lua
-- 'Sync' files between instances and ignore swap
-- https://youtu.be/fm33-Pas7vI?t=193
-- autocmd on focus, checktime, autoread
-- vim.cmd('set shortmess+=A')   -- ignoire annoying swapfile messages.
vim.opt.shortmess:append("A")
vim.o.autoread = true
vim.cmd([[au FocusGained * silent! checktime]])
```

However, in the auto-session `plugin` file these settings are all reverted back to standard and so my desired behavior of handling swaps etc breaks. I don't know if it would be possible to have a flag that omits the reverting back to standard `coptions` or something of the kind. (It might be bad for other things though...).
