### ISSUE TITLE
The session might be corrupted: No buffers were wiped out

### ISSUE THREAD

**Issue by piersolenski** [rmagatti/auto-session#331]
I keep getting this error from time to time when opening Neovim:

```
auto-session ERROR: Error restoring session! The session might be corrupted.
Disabling auto save. Please check for errors in your config. Error:
vim/_editor.lua:0: nvim_exec2()../Users/piers/.local/share/nvim/sessions/%Users%piers%.dotfiles.vim, line 44: Vim(bwipeout):E517: No buffers were wiped out: bwipe 1
```

**To Reproduce**
This seems to happen sporadically upon opening vim, I'm not sure how to reproduce it.

**Expected behavior**
There is no corruption, the session restores correctly.

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal`
 - OS. e.g `uname -a`: `Darwin RogueOne 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64`

 - Neovim version `nvim --version`:
 ```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189
```

Is there a way to debug what is going on here?

**Comment by cameronr** [comment]
Thanks for the report. When it happens, can you post the contents of your session file (`/Users/piers/.local/share/nvim/sessions/%Users%piers%.dotfiles.vim`)?

**Comment by piersolenski** [comment]
Thanks for the quick response! This is another session where it just occurred, but with the same error:

```vim
let SessionLoad = 1
let s:so_save = &g:so | let s:siso_save = &g:siso | setg so=0 siso=0 | setl so=-1 siso=-1
let v:this_session=expand("<sfile>:p")
silent only
silent tabonly
cd ~/Projects/timeline-cms
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
let s:shortmess_save = &shortmess
if &shortmess =~ 'A'
  set shortmess=aoOA
else
  set shortmess=aoO
endif
badd +3 .eslintrc.json
badd +1 ~/Projects/timeline-cms/src/utils/constants.ts
badd +41 package.json
badd +5 ~/Projects/timeline-cms/src/hooks/useEpisodeSearch.ts
badd +2 ~/Projects/timeline-cms/src/utils/linkPreviews/index.ts
argglobal
%argdel
edit ~/Projects/timeline-cms/src/utils/linkPreviews/index.ts
argglobal
balt ~/Projects/timeline-cms/src/hooks/useEpisodeSearch.ts
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let &fdl = &fdl
let s:l = 2 - ((1 * winheight(0) + 24) / 48)
if s:l < 1 | let s:l = 1 | endif
keepjumps exe s:l
normal! zt
keepjumps 2
normal! 0
tabnext 1
if exists('s:wipebuf') && len(win_findbuf(s:wipebuf)) == 0 && getbufvar(s:wipebuf, '&buftype') isnot# 'terminal'
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=1 winwidth=20
let &shortmess = s:shortmess_save
let s:sx = expand("<sfile>:p:r")."x.vim"
if filereadable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &g:so = s:so_save | let &g:siso = s:siso_save
set hlsearch
nohlsearch
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
```

**Comment by cameronr** [comment]
Interesting, I assume the error was on line 43 in this case? If I'm reading the session code correctly, that line is trying to clean up a temporary buffer potentially created during the restore (it checks for it on line 6). If that's right, the question is why is that throwing an error, saying it can't wipeout that buffer. I wonder if something is interfering with that buffer in some way. A few questions:

1. After getting the error, what happens if you restore the session again by running `:SessionRestore`? Does it throw an error again or no?
2. What do you have happening on startup / VimEnter? Do you have a dashboard plugin or anything else that is display at startup?
3. Do you have any interesting AutoCmds / plugins that do something on Buf* or Win* events?
4. What does your auto-session config look like?
5. What package manager are you using?

Lastly, it's probably not related but the recommended session options are:
```lua
vim.o.sessionoptions = 'blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions'
```

`localoptions` makes sure that buffer local options are restored (not having that can cause issues with syntax highlighting, see #204)

`winpos` I think is only relevant for some gui based versions (restores overall nvim window position) but no downside to include in case you're using one

**Comment by samuellawerentz** [comment]
+1 Facing this issue too. I use a plugin which shuts down unused buffers. 
This plugin - https://github.com/axkirillov/hbac.nvim

I'm not sure if it's related.

![image](https://github.com/user-attachments/assets/4d8408c9-8eb1-4772-9d66-6443372dd3c3)

**Comment by cameronr** [comment]
@samuellawerentz Thanks for the report and the pointer to [axkirillov/hbac.nvim](https://github.com/axkirillov/hbac.nvim). Installing that plugin will cause this issue whenever restoring a session with  more than `threshold` buffers. I think this is a bug in `hbac` as it will happen even if manually sourcing the session file.

I'll open an issue in `hbac`.

**Comment by cameronr** [comment]
I submitted a [PR for hbac](https://github.com/axkirillov/hbac.nvim/pull/28) in case they're interested. In the meantime, you can try my fork of hbac (`cameronr/hbac.nvim`) to see if that fixes it for you.

**Comment by samuellawerentz** [comment]
Great! I used your fork of hbac. Seems to work fine. 

Thank you for the resolution..!

**Comment by piersolenski** [comment]
@cameronr I actually do, and having removed it and tested for the last few days, the error does seem to have disappeared. on a side note, I had suspected this plugin might be at fault before and disabled via `cond = false`, however the problem kept recurring - so perhaps I've misassumed how that works at a deeper level 🤔 

Anyway, thanks for the fork and quick response - I think we can safely close this!
