### ISSUE TITLE
[BUG] Restore fail using along with `luukvbaal/statuscol.nvim`

### ISSUE THREAD

**Issue by KevinNitroG** [rmagatti/auto-session#353]
**Describe the bug**
Restore fails with last empty buffer (no files opened) while using along with https://github.com/luukvbaal/statuscol.nvim.

**To Reproduce**
1. Open nvim
2. Open files
3. Close all files. NvChad will create the empty buffer.
4. Quit nvim
5. Open nvim
6. Error appear

**Expected behavior**
Nvim should start normally without error.

**Screenshots**
![image](https://github.com/user-attachments/assets/783eb6ab-b686-4f2a-931d-bd9515907d1b)

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `  sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions`
 - OS. e.g `uname -a`: `Linux kevostro-arch 6.10.2-arch1-2 #1 SMP PREEMPT_DYNAMIC Sat, 03 Aug 2024 17:56:17 +0000 x86_64 GNU/Linux`
 - Neovim version `nvim --version`: `v0.10.1` `LuaJIT 2.1.1720049189`
 - URL to your current config (if public): https://github.com/KevinNitroG/Alexis12119-nvim

**Comment by cameronr** [comment]
Can you share the contents of the session file it's loading (should be in `~/.local/share/nvim/sessions/`)?

I suspect the issue is that the `luukvbaal/statuscol.nvim` isn't getting loaded because the `FilePost` user event in `nvchad` doesn't fire when the buftype is `nofile`:

https://github.com/NvChad/NvChad/blob/fea5d02d2d07b148243c058d1b8b775f9cccac5e/lua/nvchad/autocmds.lua#L14-L15

And I bet the session file has something is expecting statuscol to be loaded.

**Comment by cameronr** [comment]
I spent more time looking into this. I think this is an issue with `statuscol` putting things in the local options that aren't lazy loading resilient, as described here in the link above. I submitted a PR but if they don't merge, you can fix the error by requiring `statuscol` before restoring a session by adding this to your auto-session config:

```lua
      pre_save_cmds = {
        require('statuscol'),
      },
```

**Comment by cameronr** [comment]
@tan-wei workaround for `statuscol` issue is above (assuming they don't merge my PR)

**Comment by KevinNitroG** [comment]
Thank you guys!

**Comment by cameronr** [comment]
[`statuscol` was updated to make it resilient to lazy loading](https://github.com/luukvbaal/statuscol.nvim/issues/136).

There is small detail, tho, people with saved sessions that have the original `setlocal statuscolumn=%!v:lua.StatusCol()` will get an error loading those sessions (because `StatusCol` no longer exists) until they save a new session with the new value. Not a huge deal but worth documenting here in case ppl search for this issue in the future.

If you get a statuscol error after loading your session, just run `:SessionSave` to save a session with the new value (must have at least one buffer open that uses statuscol) to write out session with the updated `statuscolumn` value.
