### ISSUE TITLE
[BUG] The file before the last is always opened

### ISSUE THREAD

**Issue by ilya-siluyanov** [rmagatti/auto-session#373]
**Describe the bug**

After I reopen `nvim`, file before the last opens.

**To Reproduce**

I reproduce the bug on the [video](https://github.com/user-attachments/assets/8eb734c8-0c3f-4acc-841e-84680209c91f).

nvim config link provided below.

**Expected behavior**

The last visible file should be opened.

**Checkhealth**
Paste the contents of `checkhealth auto-session` here

```text
auto-session: require("auto-session.health").check()

vim options ~
- OK vim.o.sessionoptions

Lazy.nvim settings ~
- OK Lazy.nvim support is enabled
- OK auto-session is not lazy loaded

Config ~
- OK 
  {
    suppressed_dirs = { "~/", "~/Projects", "~/Downloads", "/" }
  }

General Info ~
- Session directory: /Users/ilyasiluyanov/.local/share/nvim/sessions/
- Current session: /Users/ilyasiluyanov/projects/sbx/a
- Current session file: /Users/ilyasiluyanov/.local/share/nvim/sessions/%2FUsers%2Filyasiluyanov%2Fprojects%2Fsbx%2Fa.vim

```

**Baseline (please complete the following information):**
- Result of `set sessionoptions?`: `blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions`
- OS. e.g `uname -a`: `Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May 1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64`
- Neovim version `nvim --version`: `v0.10.1`
- URL to your current config (if public): [link](https://github.com/ilya-siluyanov/nvim/tree/new-config)

**Comment by cameronr** [comment]
Thanks for the report, especially with the video and link to your dotfiles. That made looking into this very easy.

I think it's an issue with `neotree` where it's making the wrong file the active buffer, maybe because the session is being loaded at the same time. You can confirm that by running just `nvim` in the directory (no `.` argument) and the expected buffer should be displayed.

There are a few options to fix:

1. lazy load neotree so it doesn't conflict with loading the session (specifying `keys` or a `cmd` will cause Lazy.nvim to lazy load a plugin):
```lua
return {
  {
    "nvim-neo-tree/neo-tree.nvim",
    keys = {
      { '<leader>e', '<cmd>Neotree toggle reveal<CR>', desc = 'NeoTree' },
    },
    cmd = 'Neotree',
    opts = {
      close_if_last_window = true,
    },
    window = {
      mappings = {
        ["<C-t>"] = "open_vsplit",
      },
    },
  },”
}
```

That works best if you don't always want neotree open.

2. If you always want neotree open, then make the changes in 1 so neotree is lazy loaded but then also change your auto-session config to open neotree after it starts:
```lua
return {
  {
    'rmagatti/auto-session',
    lazy = false,
    dependencies = {
      'nvim-telescope/telescope.nvim', -- Only needed if you want to use session lens
    },

    ---enables autocomplete for opts
    ---@module "auto-session"
    ---@type AutoSession.Config
    opts = {
      suppressed_dirs = { '~/', '~/Projects', '~/Downloads', '/' },
      -- log_level = 'debug',

      -- called when no session is restored
      no_restore_cmds = {
        'Neotree show',
      },

      -- called after a session is restored
      post_restore_cmds = {
        'Neotree show',
      },
    },
  },
}
```
