### ISSUE TITLE
Project.nvim integration or similar

### ISSUE THREAD

**Issue by Chaitanyabsprip** [rmagatti/auto-session#56]
It would be helpful and intuitive if this plugin can selectively auto-save sessions only for projects. one way of implementing this could be having a check like, if `cwd` contains values from `root_pattern_list` then save session.

**Comment by rmagatti** [comment]
This plugin already has a feature to do the opposite of that, so _not_ saving a session for specific paths.
It'd be fairly simple to add an _optional_ feature to _only_ save sessions for specified paths. I'd gladly review a PR for this if anyone's interested in working on it!

Otherwise I'll mark this as a feature request and might get to it at some point 😊

**Comment by Chaitanyabsprip** [comment]
I could look into this, can you point me to the right module in which I can find the code for the counter feature?

**Comment by rmagatti** [comment]
Check out these spots:
- https://github.com/rmagatti/auto-session/blob/main/lua/auto-session.lua#L92
- https://github.com/rmagatti/auto-session/blob/main/lua/auto-session.lua#L132

**Comment by Chaitanyabsprip** [comment]
I have implemented this functionality, can you test it?

**Comment by rmagatti** [comment]
Threw in some comments in the PR.

**Comment by rmagatti** [comment]
I think this was effectively closed by #58
